apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization                        
commonLabels:                              
  app: login-service                               
resources:                                 
  - deployment.yaml                        
  - service.yaml                           
configMapGenerator:                        
  - name: login-service-map                        
    literals:                              
      - KEY=value                          
