apiVersion: v1        
kind: Service         
metadata:             
  name: login-service         
spec:                 
  selector:           
    app: login-service        
  ports:              
    - port: 8083   
      targetPort: 8083